package metamodels;

import decavun2.analysis.meta.StatisticsMetaModel;
import decavun2.analysis.meta.StatisticsMetaModelAliased;
import decavun2.objects.meta.DriverReportMetaModel;
import decavun2.objects.meta.DriverReportMetaModelAliased;
import decavun2.objects.meta.RepairMetaModel;
import decavun2.objects.meta.RepairMetaModelAliased;
import decavun2.objects.meta.VehicleMetaModel;
import decavun2.objects.meta.VehicleMetaModelAliased;
import decavun2.personnel.meta.PersonMetaModel;
import decavun2.personnel.meta.PersonMetaModelAliased;
import java.lang.String;
import javax.annotation.processing.Generated;
import ua.com.fielden.platform.security.user.meta.UserMetaModel;
import ua.com.fielden.platform.security.user.meta.UserMetaModelAliased;

/**
 * Generation datetime: 21-01-2023 00:12:06.499 EET
 * <p>
 * Generated by {@link ua.com.fielden.platform.processors.metamodel.MetaModelProcessor}.
 */
@Generated(
        value = "ua.com.fielden.platform.processors.metamodel.MetaModelProcessor",
        date = "2023-01-21T00:12:06.499+02:00"
)
public final class MetaModels {
    public static final DriverReportMetaModel DriverReport_ = new DriverReportMetaModel();

    public static final PersonMetaModel Person_ = new PersonMetaModel();

    public static final RepairMetaModel Repair_ = new RepairMetaModel();

    public static final StatisticsMetaModel Statistics_ = new StatisticsMetaModel();

    public static final UserMetaModel User_ = new UserMetaModel();

    public static final VehicleMetaModel Vehicle_ = new VehicleMetaModel();

    public static DriverReportMetaModelAliased DriverReport_(final String alias) {
        final DriverReportMetaModelAliased aliased = new DriverReportMetaModelAliased(alias);
        return aliased;
    }

    public static PersonMetaModelAliased Person_(final String alias) {
        final PersonMetaModelAliased aliased = new PersonMetaModelAliased(alias);
        return aliased;
    }

    public static RepairMetaModelAliased Repair_(final String alias) {
        final RepairMetaModelAliased aliased = new RepairMetaModelAliased(alias);
        return aliased;
    }

    public static StatisticsMetaModelAliased Statistics_(final String alias) {
        final StatisticsMetaModelAliased aliased = new StatisticsMetaModelAliased(alias);
        return aliased;
    }

    public static UserMetaModelAliased User_(final String alias) {
        final UserMetaModelAliased aliased = new UserMetaModelAliased(alias);
        return aliased;
    }

    public static VehicleMetaModelAliased Vehicle_(final String alias) {
        final VehicleMetaModelAliased aliased = new VehicleMetaModelAliased(alias);
        return aliased;
    }
}
