package metamodels;

import decavun2.objects.meta.DriverReportMetaModel;
import decavun2.objects.meta.DriverReportMetaModelAliased;
import decavun2.objects.meta.OrderMetaModel;
import decavun2.objects.meta.OrderMetaModelAliased;
import decavun2.objects.meta.RepairMetaModel;
import decavun2.objects.meta.RepairMetaModelAliased;
import decavun2.personnel.meta.PersonMetaModel;
import decavun2.personnel.meta.PersonMetaModelAliased;
import java.lang.String;
import javax.annotation.processing.Generated;
import ua.com.fielden.platform.security.user.meta.UserMetaModel;
import ua.com.fielden.platform.security.user.meta.UserMetaModelAliased;

/**
 * Generation datetime: 20-01-2023 19:51:17.280 EET
 * <p>
 * Generated by {@link ua.com.fielden.platform.processors.metamodel.MetaModelProcessor}.
 */
@Generated(
        value = "ua.com.fielden.platform.processors.metamodel.MetaModelProcessor",
        date = "2023-01-20T19:51:17.280+02:00"
)
public final class MetaModels {
    public static final DriverReportMetaModel DriverReport_ = new DriverReportMetaModel();

    public static final OrderMetaModel Order_ = new OrderMetaModel();

    public static final PersonMetaModel Person_ = new PersonMetaModel();

    public static final RepairMetaModel Repair_ = new RepairMetaModel();

    public static final UserMetaModel User_ = new UserMetaModel();

    public static DriverReportMetaModelAliased DriverReport_(final String alias) {
        final DriverReportMetaModelAliased aliased = new DriverReportMetaModelAliased(alias);
        return aliased;
    }

    public static OrderMetaModelAliased Order_(final String alias) {
        final OrderMetaModelAliased aliased = new OrderMetaModelAliased(alias);
        return aliased;
    }

    public static PersonMetaModelAliased Person_(final String alias) {
        final PersonMetaModelAliased aliased = new PersonMetaModelAliased(alias);
        return aliased;
    }

    public static RepairMetaModelAliased Repair_(final String alias) {
        final RepairMetaModelAliased aliased = new RepairMetaModelAliased(alias);
        return aliased;
    }

    public static UserMetaModelAliased User_(final String alias) {
        final UserMetaModelAliased aliased = new UserMetaModelAliased(alias);
        return aliased;
    }
}
